apiVersion: v1
kind: Secret
metadata:
  name: ems-secrets
  namespace: ems-production
type: Opaque
stringData:
  DATABASE_URL: "postgresql://ems_admin:REPLACE_WITH_SECURE_PASSWORD@postgres-service:5432/ems_db?schema=public"
  JWT_ACCESS_SECRET: "REPLACE_WITH_64_CHAR_ACCESS_SECRET"
  JWT_REFRESH_SECRET: "REPLACE_WITH_64_CHAR_REFRESH_SECRET"
  S3_ACCESS_KEY: "REPLACE_WITH_MINIO_USER"
  S3_SECRET_KEY: "REPLACE_WITH_MINIO_SECRET"
